import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:4000";

const fallbackMenu = {
  coffee: [["House Cappuccino","Double espresso, silky milk, cocoa dust","₹180"],["Honey Cinnamon Latte","Espresso, steamed milk, local honey","₹220"],["Cold Brew","18-hour steep, smooth & chocolatey","₹190"],["Orange Americano","Espresso, sparkling orange, ice","₹210"]],
  breakfast: [["Avocado Sourdough","Smashed avocado, lemon, chili, seeds","₹320"],["Berry Granola Bowl","Greek yogurt, berries, toasted granola","₹280"],["Butter Croissant","Classic laminated pastry, baked fresh","₹150"],["Mushroom Toast","Garlic mushrooms, ricotta, herbs","₹290"]],
  lunch: [["Roasted Veg Sandwich","Focaccia, roast vegetables, pesto","₹340"],["Pesto Pasta","Basil pesto, parmesan, cherry tomatoes","₹390"],["Green Goddess Salad","Leaves, avocado, seeds, herb dressing","₹320"],["Tomato Melt","Sourdough, aged cheddar, tomato jam","₹280"]],
  sweet: [["Cinnamon Roll","Brown sugar, cinnamon, vanilla glaze","₹170"],["Basque Cheesecake","Creamy center, caramelized top","₹260"],["Dark Chocolate Tart","70% cocoa, sea salt, cream","₹240"],["Lemon Loaf","Bright lemon, butter, sugar glaze","₹160"]]
};

function Reveal({children,className="",direction="up"}) {
  const ref=useRef(null), [show,setShow]=useState(false);
  useEffect(()=>{const o=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShow(true);o.disconnect()}},{threshold:.12,rootMargin:"0px 0px -40px 0px"});if(ref.current)o.observe(ref.current);return()=>o.disconnect()},[]);
  return <div ref={ref} className={`${className} reveal-${direction} ${show?"revealed":""}`}>{children}</div>;
}
function Stagger({children,className=""}) {
  return <Reveal className={`${className} stagger`}>{children}</Reveal>;
}
const MenuIcon=()=> <svg viewBox="0 0 48 48"><rect x="10" y="8" width="28" height="32" rx="5" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M16 17h16M16 24h16M16 31h10" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>;
const TableIcon=()=> <svg viewBox="0 0 48 48"><path d="M8 17h32M12 17v8M36 17v8M15 25c0 6 3 9 9 9s9-3 9-9M19 34v6M29 34v6" fill="none" stroke="currentColor" strokeWidth="3.2" strokeLinecap="round"/></svg>;

function App(){
  const [mobile,setMobile]=useState(false),[category,setCategory]=useState("coffee"),[menu,setMenu]=useState(fallbackMenu),[toast,setToast]=useState(""),[progress,setProgress]=useState(0);
  const [today,setToday]=useState("");
  useEffect(()=>{fetch(`${API}/api/menu`).then(r=>r.ok?r.json():Promise.reject()).then(setMenu).catch(()=>{})},[]);
  useEffect(()=>{const d=new Date();setToday(new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10));const f=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max?scrollY/max*100:0)};addEventListener("scroll",f,{passive:true});f();return()=>removeEventListener("scroll",f)},[]);
  const submit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.currentTarget));try{const r=await fetch(`${API}/api/reservations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.message);e.currentTarget.reset();setToast(`Thanks, ${payload.name}! Reservation #${d.id} received.`)}catch(err){setToast(err.message||"Could not submit reservation.")}setTimeout(()=>setToast(""),4200)};
  return <>
    <div className="scroll-progress" style={{width:`${progress}%`}}/>
    <header><div className="container nav"><a className="brand" href="#home"><span className="brand-mark">B&B</span>Brew & Bloom</a><nav className={mobile?"open":""}><ul>{[["Menu","menu"],["Our Story","story"],["Reviews","reviews"],["Visit","visit"]].map(([x,id])=><li key={id}><a href={`#${id}`} onClick={()=>setMobile(false)}>{x}</a></li>)}</ul></nav><div className="nav-actions"><a className="btn btn-primary" href="#booking">Book a Table</a><button className="icon-btn" onClick={()=>setMobile(!mobile)} aria-label="Toggle menu">☰</button></div></div></header>
    <main id="home">
      <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">Coffee • Food • Community</span><h1>A little more <em>slow</em> in every sip.</h1><p>Specialty coffee, seasonal plates, and a warm corner to stay awhile. Brewed carefully, served simply, made for good conversations.</p><div className="hero-actions">
        <a className="btn btn-primary hero-cta hero-menu-btn" href="#menu"><span className="btn-label">Explore the Menu</span><span className="btn-icon"><MenuIcon/></span><span className="btn-arrow">→</span></a>
        <a className="btn btn-secondary hero-cta hero-table-btn" href="#booking"><span className="btn-label">Find a Table</span><span className="btn-icon"><TableIcon/></span></a>
      </div><div className="hero-meta"><div><strong>Mon–Fri · 7am–9pm</strong><span>Sat–Sun · 8am–10pm</span></div><div><strong>Freshly roasted</strong><span>Small-batch local beans</span></div></div></div><div className="hero-art" aria-hidden="true"><span className="leaf l1"/><span className="leaf l2"/><span className="bean one"/><span className="bean two"/><div className="cup"><div className="steam"/><div className="coffee"/></div></div></div></section>
      <section className="stats"><Stagger className="container stats-grid">{[["12+","Seasonal drinks"],["4.9/5","Guest rating"],["7 days","Open every week"],["100%","Good vibes"]].map(x=><div className="stat" key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</Stagger></section>
      <section className="menu-section" id="menu"><div className="container"><Reveal className="section-head"><span className="eyebrow">A few favorites</span><h2>Made to be enjoyed slowly.</h2><p>From your first morning flat white to a late-evening slice, everything is prepared in small batches.</p></Reveal><Reveal direction="left" className="menu-tabs">{Object.keys(menu).map(c=><button key={c} className={`tab ${category===c?"active":""}`} onClick={()=>setCategory(c)}>{c[0].toUpperCase()+c.slice(1)}</button>)}</Reveal><div className="menu-grid" key={category}>{(menu[category]||[]).map(([n,d,p])=><article className="menu-card" key={n}><div><h3>{n}</h3><p>{d}</p></div><strong className="price">{p}</strong></article>)}</div></div></section>
      <section className="experience" id="story"><div className="container experience-grid"><Reveal direction="left" className="experience-art"/><div><Reveal className="section-head"><span className="eyebrow">Our story</span><h2>A neighborhood café with a slower rhythm.</h2><p>Brew & Bloom started with a simple idea: make excellent coffee, serve honest food, and create a room people actually want to linger in.</p></Reveal><Stagger className="feature-list">{[["☕","Thoughtful coffee","Single-origin beans, dialed in daily and brewed to order."],["🥐","Fresh kitchen","Seasonal ingredients and comforting plates made in-house."],["🌿","Easy atmosphere","Natural textures, leafy corners, and plenty of time to stay awhile."]].map(x=><div className="feature" key={x[1]}><div className="feature-icon">{x[0]}</div><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</Stagger></div></div></section>
      <section id="reviews"><div className="container"><Reveal className="section-head"><span className="eyebrow">Kind words</span><h2>Come for the coffee. Stay for the feeling.</h2></Reveal><Stagger className="reviews-grid">{[["Rhea M.","The kind of place where you sit down for twenty minutes and somehow spend the whole afternoon."],["Arjun K.","Beautifully balanced coffee, genuinely friendly staff, and the cinnamon roll is dangerous."],["Mia S.","Perfect for a quiet work session. Great light, strong Wi-Fi, and food that actually tastes fresh."]].map(x=><article className="review" key={x[0]}><div className="stars">★★★★★</div><p>“{x[1]}”</p><strong>— {x[0]}</strong></article>)}</Stagger></div></section>
      <section className="booking" id="booking"><div className="container booking-grid"><Reveal direction="left" className="booking-copy"><span className="eyebrow">Make it a moment</span><h2>Reserve a table for your next slow morning.</h2><p>For groups of 8 or more, call us directly so we can arrange the best table for you.</p><div className="contact-mini"><span>📍 18 Willow Lane, Your City</span><span>☎ +91 98765 43210</span><span>✉ hello@brewandbloom.example</span></div></Reveal><Reveal direction="right"><form className="form-card" onSubmit={submit}><div className="form-grid"><label>Your name<input name="name" required placeholder="e.g. Aisha"/></label><label>Guests<select name="guests" defaultValue="2 people">{["1 person","2 people","3 people","4 people","5–7 people","8+ people"].map(x=><option key={x}>{x}</option>)}</select></label><label>Date<input name="date" type="date" required min={today}/></label><label>Time<select name="time" defaultValue="8:00 PM">{["8:00 AM","9:30 AM","11:00 AM","1:00 PM","3:30 PM","6:00 PM","8:00 PM"].map(x=><option key={x}>{x}</option>)}</select></label><label className="form-full">Notes<textarea name="notes" placeholder="Birthday, window seat, dietary notes…"/></label></div><button className="btn btn-primary" type="submit">Request a Reservation →</button><p className="form-note">Connected to the Node.js reservation API and Python analytics service.</p></form></Reveal></div></section>
    </main>
    <footer id="visit"><div className="container"><div className="footer-grid"><div className="footer-brand"><div className="brand"><span className="brand-mark">B&B</span>Brew & Bloom</div><p>Specialty coffee and everyday comfort, served in a room made for lingering.</p></div><div><h4>Explore</h4><ul><li><a href="#menu">Menu</a></li><li><a href="#story">Our Story</a></li><li><a href="#reviews">Reviews</a></li></ul></div><div><h4>Visit</h4><ul><li>18 Willow Lane</li><li>Your City</li><li>Mon–Fri · 7am–9pm</li><li>Sat–Sun · 8am–10pm</li></ul></div><div><h4>Say hello</h4><ul><li><a href="tel:+919876543210">+91 98765 43210</a></li><li><a href="mailto:hello@brewandbloom.example">hello@brewandbloom.example</a></li><li><a href="#booking">Book a table →</a></li></ul></div></div><div className="copyright"><span>© 2026 Brew & Bloom Café. All rights reserved.</span><span>Made for slow mornings.</span></div></div></footer>
    {toast&&<div className="toast show" role="status">{toast}</div>}
  </>;
}
createRoot(document.getElementById("root")).render(<App/>);
